a=int(input("enter 1st number:"))
b=int(input("enter 2nd number:"))
c=int(input("enter 3rd number:"))
if(a>b and a>c): print(a,"is greater")
elif(b>a and b>c): print(b,"is greater")
else: print(c,"is greater")
if(a<b and a<c): print(a,"is lesser")
elif(b<c and b<a): print(b,"is lesser")
else: print(c,"is lesser")